### ISSUE TITLE
How to use asdff with SDXL

### ISSUE THREAD

**Issue by elcolie** [Bing-su/asdff#6]
How to use `asdff` aka `ADetailer` with `StableDiffusionXLPipeline`?

**Comment by Bing-su** [comment]
언젠가 제 컴퓨터 사양이 더 좋아지면 해보겠습니다. adetailer도 SDXL에 대해서는 테스트되지 않고 있습니다.

**Comment by elcolie** [comment]
> 언젠가 제 컴퓨터 사양이 더 좋아지면 해보겠습니다. adetailer도 SDXL에 대해서는 테스트되지 않고 있습니다.

>>I'll give it a try someday when my computer specs get better. adetailer is also not tested for SDXL.

Thank you.

**Comment by John0x** [comment]
@Bing-su did you have chance to test it yet?
